# Generated by Django 6.0 on 2025-12-03 18:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ciclo', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Facultad')),
            ],
            options={
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Universidad')),
                ('siglas', models.CharField(max_length=20, verbose_name='Siglas (Ej: UDH)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universidades/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('ESTUDIANTE', 'Estudiante'), ('MENTOR', 'Mentor')], default='ESTUDIANTE', max_length=15, verbose_name='Rol')),
                ('codigo_alumno', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Alumno / Institucional')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Carrera')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='api.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_material', models.CharField(choices=[('RESUMEN', 'Resumen Sintetizado'), ('GUIA', 'Guía de Estudio'), ('METODO', 'Método de Estudio'), ('SIMULACRO', 'Simulacro/Cuestionario')], max_length=20)),
                ('archivo', models.FileField(upload_to='materiales/%Y/%m/')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En Revisión'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=20)),
                ('atribucion_derechos', models.CharField(blank=True, max_length=255, verbose_name='Atribución / Copyright')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conteo_descargas', models.PositiveIntegerField(default=0)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='api.curso')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material de Estudio',
                'verbose_name_plural': 'Materiales de Estudio',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono / WhatsApp')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Perfil de LinkedIn')),
                ('portfolio', models.URLField(blank=True, null=True, verbose_name='Portafolio / GitHub')),
                ('ciclo_actual', models.PositiveIntegerField(default=1, verbose_name='Ciclo Actual')),
                ('objetivo_academico', models.CharField(blank=True, choices=[('MEJORAR_PROMEDIO', 'Mejorar Ponderado'), ('PASAR_CURSO', 'Pasar Cursos'), ('MANTENER_PROMEDIO', 'Mantener Ponderado'), ('APRENDER_METODO', 'Aprender Métodos de Estudio')], max_length=30, null=True)),
                ('biografia', models.TextField(blank=True, verbose_name='Sobre mí')),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='api.carrera', verbose_name='Carrera Profesional')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SesionMentoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200, verbose_name='Tema Específico')),
                ('fecha_programada', models.DateTimeField()),
                ('enlace_reunion', models.URLField(blank=True, verbose_name='Link de Reunión')),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('PROGRAMADA', 'Programada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=20)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación/Rechazo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias_tomadas', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(limit_choices_to={'rol': 'MENTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentorias_impartidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Mentoría',
                'verbose_name_plural': 'Sesiones de Mentoría',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Estrellas (1-5)')),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='api.materialestudio')),
                ('sesion_mentoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='api.sesionmentoria')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
            },
        ),
        migrations.AddField(
            model_name='facultad',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultades', to='api.universidad'),
        ),
    ]
