# Generated by Django 6.0 on 2025-12-08 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Enunciado de la Pregunta')),
                ('tipo', models.CharField(choices=[('OPCION_MULTIPLE', 'Opción Múltiple (Una correcta)'), ('VERDADERO_FALSO', 'Verdadero / Falso'), ('SELECCION_MULTIPLE', 'Selección Múltiple (Varias correctas)')], default='OPCION_MULTIPLE', max_length=20)),
                ('puntaje', models.PositiveIntegerField(default=10, verbose_name='Puntos por responder bien')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='api.carrera'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='medalla_actual',
            field=models.CharField(default='Bit (2^1)', max_length=50, verbose_name='Medalla Actual'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nivel_confianza',
            field=models.CharField(default='Novato', max_length=50, verbose_name='Nivel de Confianza (Tier)'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='puntos_reputacion',
            field=models.IntegerField(default=0, verbose_name='Puntos Meteorite'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='quizzes_completados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='racha_estudio',
            field=models.PositiveIntegerField(default=0, verbose_name='Días en Racha'),
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es Correcta?')),
                ('retroalimentacion', models.TextField(blank=True, null=True, verbose_name='Explicación / Feedback')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='api.pregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
            },
        ),
        migrations.CreateModel(
            name='PreguntaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('RESUELTA', 'Resuelta (Mejor Respuesta Seleccionada)'), ('CERRADA', 'Cerrada por Moderación')], default='ABIERTA', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Etiquetas (Tags)')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_foro', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_foro', to='api.curso')),
            ],
            options={
                'verbose_name': 'Pregunta de Foro',
                'verbose_name_plural': 'Preguntas de Foro',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('generado_por_ai', models.BooleanField(default=False, verbose_name='Generado por IA')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes_creados', to=settings.AUTH_USER_MODEL)),
                ('material_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes_derivados', to='api.materialestudio')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='api.quiz'),
        ),
        migrations.CreateModel(
            name='IntentoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.FloatField(default=0.0)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_quizzes', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='api.quiz')),
            ],
            options={
                'verbose_name': 'Intento de Quiz',
                'verbose_name_plural': 'Intentos de Quizzes',
            },
        ),
        migrations.CreateModel(
            name='RespuestaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('es_mejor_respuesta', models.BooleanField(default=False, verbose_name='Mejor Respuesta (La Corona)')),
                ('puntos_votos', models.IntegerField(default=0, verbose_name='Conteo de Votos (Cache)')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_foro', to=settings.AUTH_USER_MODEL)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='api.preguntaforo')),
            ],
            options={
                'verbose_name': 'Respuesta de Foro',
                'verbose_name_plural': 'Respuestas de Foro',
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.SmallIntegerField(choices=[(1, 'Util (+1)'), (-1, 'No Util (-1)')])),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='api.respuestaforo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'respuesta')},
            },
        ),
    ]
