# Generated by Django 6.0 on 2025-12-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pregunta_curso_carrera_perfil_medalla_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cursos_inscritos',
            field=models.ManyToManyField(blank=True, related_name='estudiantes_inscritos', to='api.curso'),
        ),
    ]
